setup:
		mkdir log

pack:
		cd public/js/ && curl -X POST -s --data-urlencode 'input@application.js' http://javascript-minifier.com/raw > application.min.js
		cd public/css/ && curl -X POST -s --data-urlencode 'input@styles.css' http://cssminifier.com/raw > styles.min.css
